=== miloradradovic/XML_TIM7/documents/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://resenja/resenje" xmlns:ra="http://resenja/resenje">

    <xs:element name="resenja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resenje" type="ra:Tresenje"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Tresenje">
        <xs:sequence>
            <xs:element name="uvodne_informacije" type="ra:Tuvodne_informacije"/>
            <xs:element name="podaci_o_resenju" type="ra:Tpodaci_o_resenju"/>
            <xs:element name="podaci_o_obrazlozenju" type="ra:Tpodaci_o_obrazlozenju"/>
            <xs:element name="poverenik" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="broj">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{3}\-[0-9]{2}\-[0-9]{4}\/[0-9]{4}\-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="tip_resenja" type="xs:string"/>
        <xs:attribute name="datum" type="xs:string"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tuvodne_informacije">
        <xs:sequence>
            <xs:element name="lice" type="xs:string"/>
            <xs:element name="adresa" type="ra:Tadresa"/>
            <xs:element name="datum" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="clan" type="ra:Tclan"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tpodaci_o_resenju">
        <xs:sequence>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="tacka" type="ra:Ttacka"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tpodaci_o_obrazlozenju">
        <xs:sequence>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element name="predmet_zalbe" type="ra:Tpredmet_zalbe"/>
            <xs:element name="postupak_poverenika" type="ra:Tppostupak_poverenika"/>
            <xs:element name="odluka"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tadresa">
        <xs:sequence>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="ulica">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="broj" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tclan">
        <xs:sequence>
            <xs:element minOccurs="0" name="stav" type="ra:Tstav"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="tacka">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="broj" type="xs:int"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="broj" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="Tstav" mixed="true">
        <xs:sequence>
            <xs:element minOccurs="0" name="tacka">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="broj" type="xs:int"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="broj" type="xs:int"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="Ttacka">
        <xs:sequence>
            <xs:element name="lice" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="mesto" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="broj" type="xs:int"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="Tpredmet_zalbe">
        <xs:choice maxOccurs="unbounded">
            <xs:element maxOccurs="unbounded" name="datum" type="xs:string"/>
            <xs:element name="lice" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Tppostupak_poverenika" mixed="true">
        <xs:sequence>
            <xs:element name="datum" type="xs:string"/>
            <xs:element name="lice" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="clan" type="ra:Tclan" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="Todluka">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="datum" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="lice" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="clan" type="ra:Tclan"/>
            <xs:element name="stav" type="ra:Tstav"/>
            <xs:element name="iznos">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]+,[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== miloradradovic/XML_TIM7/XML_dom/data/xml/resenje_out.xml
<?xml version="1.0" encoding="UTF-8"?><resenja xmlns="http://resenja/resenje" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://resenja/resenje ../xsd/resenje.xsd">
  <resenje broj="071-01-1114/2020-03" datum="" tip_resenja="">
    <uvodne_informacije/>
    <podaci_o_resenju>
      <naslov/>
      <tacka broj="1"/>
      <tacka broj="2"/>
    </podaci_o_resenju>
    <podaci_o_obrazlozenju>
      <naslov/>
      <predmet_zalbe/>
      <postupak_poverenika/>
      <odluka/>
    </podaci_o_obrazlozenju>
    <poverenik/>
  </resenje>
</resenja>

=== miloradradovic/XML_TIM7/XML_dom/data/xml/resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<resenja xmlns="http://resenja/resenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://resenja/resenje ../xsd/resenje.xsd">
    <resenje broj="071-01-1114/2020-03" tip_resenja="жалба је основана" datum="09.06.2020.">
        <uvodne_informacije>
            Повереник за информације од јавног значаја и заштиту података о личности, у поступку по алби
            коју је изјавио AA, због непоступања <lice>Учитељског факултета у Призрену</lice>са привременим седиштем 
            у <adresa><mesto>Лепосавићу</mesto>,<ulica broj="бб"> ул. Немањина </ulica></adresa>, по његовом захтеву од <datum>16.04.2020.</datum> године за приступ 
            информацијама од јавног значаја, на основу <clan broj="35">члана 35.<stav broj="1">став 1. <tacka broj="5">тачка 5.</tacka></stav></clan> Закона о слободном приступу 
            информацијама од јавног значаја („Сл. гласник РС“, бр. 120/04, 54/07, 104/09 и 36/10), а у вези са 
            <clan broj="4">чланом 4. <tacka broj="22">тачка 22.</tacka></clan>Закона о заштити података о личности („Сл. гласник РС“, број 87/18), као и <clan broj="24">члана 
            23.</clan> и <clan broj="24">члана 24. <stav broj="4">став 4.</stav></clan>Закона о слободном приступу информацијама од јавног значаја и <clan broj="173">члана 173. 
            <stav broj="2">став 2.</stav></clan> Закона о општем управном поступку („Сл. гласник РС“, бр. 18/2016 и 95/2018-аутентично 
            тумачење), доноси
        </uvodne_informacije>
        <podaci_o_resenju>
            <naslov>Р Е Ш Е Њ Е</naslov>
            <tacka broj="1">
                Налаже се <lice>Учитељском факултету у Призрену</lice> са привременим седиштем у <mesto>Лепосавићу</mesto>, да
                без одлагања, а најкасније у року од пет дана од дана пријема овог решења, обавести АА, да ли
                поседује тражене информације односно документ у коме су исте садржане, и то: Уговор о раду који
                је као последњи потписан између тог Факултета и ББ, те да му, уколико такав документ поседује
                достави копију истог електронском поштом на адресу … или поштом, с тим што ће пре достављања
                заштитити и учинити недоступним податке о личности којима би се повредило право на приватност
                лица на које се информације односе, као што су: адреса становања, лични матични број грађана, име
                оца, радни стаж, просечна оцена студирања и сл. уколико су такви подаци садржани у траженом
                документу.
            </tacka>
            <tacka broj="2">
                О извршењу решења <lice>Учитељски факултет у Призрену</lice> са привременим седиштем у
                Лепосавићу, ће обавестити Повереника у року од седам дана од пријема овог решења.
            </tacka>
        </podaci_o_resenju>
        <podaci_o_obrazlozenju>
            <naslov>О б р а з л о ж е њ е</naslov>
            <predmet_zalbe>
                АА, као тражилац информација, изјавио је дана <datum>07.05.2020.</datum> године жалбу Поверенику, због
                непоступања <lice>Учитељског факултета у Призрену</lice> са привременим седиштем у <mesto>Лепосавићу</mesto> по 
                његовом захтеву од <datum>16.04.2020.</datum> године за приступ информацијама од јавног значаја и у прилогу
                доставио копију истог.
            
            </predmet_zalbe>
            <postupak_poverenika>
                Поступајући по жалби, Повереник је дана <datum>11.05.2020.</datum> године упутио исту на изјашњење
                <lice>Учитељском факултету у Призрену</lice> са привременим седиштем у <mesto>Лепосавићу</mesto>, као органу власти у
                смислу <clan broj="3">члана 3.</clan> Закона о слободном приступу информацијама од јавног значаја и затражио да се
                изјасни о наводима жалбе, посебно о разлозима непоступања у законском року по поднетом захтеву
                у складу са одредбама <clan broj="16">члана 16. ст.1-9. или ст. 10.</clan> Закона, остављајући рок од осам дана, поводом
                чега није добио одговор.
            
            </postupak_poverenika>
            <odluka>
                
                По разматрању жалбе и осталих списа овог предмета, донета је одлука као у диспозитиву
                решења из следећих разлога:
           
                Увидом у списе предмета утврђено је да је АА, дана <datum>16.04.2020.</datum> године, поднео <lice>Учитељском
                факултету у Призрену</lice> са привременим седиштем у <mesto>Лепосавићу</mesto>, захтев за приступ информацијама
                од јавног значаја, електронском поштом, којим је тражио информације од јавног значаја, ближе
                наведенe у ставу I диспозитива овог решења.
            
                Такође је увидом у списе предмета утврђено да по захтеву жалиоца од <datum>16.04.2020.</datum> године,
                орган власти није поступио, што је био дужан да учини без одлагања, а најкасније у року од 15 дана
                од пријема захтева те да жалиоца, у смислу <clan broj="16">члана 16. <stav broj="1">став 1.</stav></clan> Закона о слободном приступу
                информацијама од јавног значаја, обавести да ли поседује тражене информације и да му, уколико
                исте поседује, стави на увид документ који исте садржи односно изда му или достави копију
                документа у коме су тражене информације садржане, или да у супротном донесе решење о одбијању
                захтева, у смислу <stav broj="10">става 10.</stav>истог члана.
            
                Имајући у виду да орган власти по захтеву жалиоца од <datum>16.04.2020.</datum> године није поступио у
                складу са наведеним одредбама Закона о слободном приступу информацијама од јавног значаја, а
                да није оправдао разлоге непоступања по поднетом захтеву, Повереник је у поступку по жалби, на
                основу <clan broj="23">члана 23.</clan> и <clan broj="24">члана 24. <stav broj="1">ст. 1.</stav> и <stav broj="4">4.</stav></clan>Закона о слободном приступу информацијама од јавног
                значаја и <clan broj="173">члана 173. <stav broj="2">ст. 2.</stav></clan> Закона о општем управном поступку, одлучио као у ставу I диспозитива
                овог решења, нашавши да је жалба основана, односно да је неспорно право жалиоца на тражене
                информације у смислу <clan broj="5">члана 5 </clan>. Закона о слободном приступу информацијама од јавног значаја, по
                коме свако има право да му буде саопштено да ли орган власти поседује или му је доступна одређена
                информација од јавног значаја, као и да му се информација, уколико је у поседу органа, учини
                доступном, на начин како је то наложено у ставу I диспозитива овог решења, што је у складу са
                одредбом <clan broj="12">члана 12.</clan> Закона о слободном приступу информацијама од јавног значаја, која предвиђа
                могућност издвајања тражене информације од јавног значаја од осталих информација садржаних у
                документу у које орган власти није дужан да тражиоцу омогући увид, јер би се доступношћу тим
                информацијама повредило право на приватност и заштиту података о личности лица на која се
                тражене информације односе.
            
                <lice>Учитељски факултет у Призрену</lice> са привременим седиштем у <mesto>Лепосавићу</mesto>, је дужан да о
                извршењу решења из става I диспозитива, обавести Повереника у складу са <clan broj="24">чланом 24. <stav broj="3">став 3.</stav> </clan>Закона
                о слободном приступу информацијама од јавног значаја.
            
                Упутство о правном средству:
            
                Против овог решења није допуштена жалба већ се, у складу са Законом о управним
                споровима, може покренути управни спор тужбом Управном суду у Београду, у року од 30 дана од
                дана пријема решења. Такса на тужбу износи <iznos valuta="dinar">390,00</iznos> динара.
            
            </odluka>
        </podaci_o_obrazlozenju>
        <poverenik>Милан Мариновић</poverenik>
    </resenje>
  
</resenja>
